/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.Mammifero;
import org.example.model.Pesce;
import org.example.model.Razza;
import org.example.model.Volatile;
import org.example.services.RegistroZoo;

public class App {

    public static void main(String[] args) {
        RegistroZoo registro=RegistroZoo.getInstance();
        registro.add(new Mammifero("Simba", Razza.LEONE));
        registro.add(new Volatile("Jhon", Razza.ACQUILA));
        registro.add(new Pesce("Nemo", Razza.PESCE_PAGLIACCIO));
        registro.add(new Mammifero("Sandokan", Razza.TIGRE));
        System.out.println(registro);
    }
}
