/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unife.oop;

import java.io.File;
import java.io.IOException;
import java.util.List;

import com.fasterxml.jackson.core.exc.StreamReadException;
import com.fasterxml.jackson.databind.DatabindException;
import com.fasterxml.jackson.databind.ObjectMapper;

import it.unife.oop.model.Libro;
import it.unife.oop.model.Scaffale;
import it.unife.oop.services.GestoreInventario;
import it.unife.oop.services.Inventario;

public class App {

    public static void main(String[] args) {
        Inventario inventario=Inventario.getInstance();
        GestoreInventario gest=GestoreInventario.getInstance();
        try {
            inventario.caricaDati("libri.json", "scaffali.json");
            gest.posizionaLibri();            
        } catch (Exception e) {
            System.out.println("Errore: "+e.getMessage());
        }

    }
}
