/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unife.oop;

import java.io.IOException;

import it.unife.oop.model.Assessore;
import it.unife.oop.model.Consigliere;
import it.unife.oop.model.Sindaco;
import it.unife.oop.services.SistemaVotazioni;

public class App {

    public static void main(String[] args) {
        SistemaVotazioni sistema = SistemaVotazioni.getInstance();

        // Aggiunta dei candidati
        sistema.aggiungiCandidato(new Sindaco(1, "Mario Rossi"));
        sistema.aggiungiCandidato(new Consigliere(2, "Luigi Bianchi"));
        sistema.aggiungiCandidato(new Assessore(3, "Anna Verdi"));

        // Simulazione delle votazioni
        sistema.vota(1);
        sistema.vota(2);
        sistema.vota(1);
        sistema.vota(3);
        sistema.vota(1);

        // Stampa dei risultati
        System.out.println("Risultati delle votazioni:");
        sistema.stampaRisultati();

        // Salvataggio su file
        try{
            sistema.salvaRisultatiSuFile("risultati.json");// se metto .json fa in jason, ma la classe di stamapre è uguale
            sistema.salvaRisultatiSuFile("risultati.txt");  //se metto .txt fa in txt
            
        }catch(IOException e){
            System.err.println(e.getMessage());
        }
        System.out.println("Risultati salvati su file.");
    }

}
